name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          jupyter: false
          use_pyproject: true